#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: mirrors scripts/render-demo-setup.ps1 (the PowerShell port, for
# terminals without bash/Git Bash). Keep the two in sync.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Render demo instance setup (ADR 0006)"

say "This wizard provisions the client-demo instance on Render's free tier:"
say "a free Postgres database + a free web service built from"
say "docker/odoo-render.Dockerfile, wired to auto-deploy on push to"
say "main/19.0. Nothing here is written to .env or GitHub secrets — every"
say "value goes straight into Render's own dashboard, since that's the only"
say "place production config for this instance lives."
note "Prerequisite: the main/19.0 branch must already exist in GitHub and be"
note "protected (passing CI required, no direct pushes — no separate reviewer,"
note "since this is a solo-maintainer repo and GitHub disallows self-approval)."
note "This is a one-time repo-admin step done via"
note "'gh api .../branches/main%2F19.0/protection' (see docs/agents/sdlc.md) —"
note "it doesn't need production credentials, so it isn't a stage in this"
note "wizard. Verify it before continuing:"
note "  gh api repos/<owner>/<repo>/branches/main%2F19.0/protection"

# ── Stage 1: Postgres database ─────────────────────────────────────────────
stage "Render: create the free Postgres database"
say "Render's free Postgres expires 30 days after creation (14-day grace"
say "period) — see ADR 0006 for why the entrypoint self-heals around this"
say "instead of relying on a Pre-Deploy Command."
open_url "https://dashboard.render.com/new/database"
step "Name it (e.g. agentic-erp-demo-db), keep the default Postgres version."
step "Set Instance Type to Free."
step "Click 'Create Database' and wait for status to become 'Available'."
step "On the database's page, open the 'Connect' tab and switch to"
step "'Internal Database URL' (same-region traffic, no bandwidth cost)."
ask ODOO_DB "Database name shown there (this becomes ODOO_DB):"
ask POSTGRES_HOST "Hostname shown there (Internal, becomes POSTGRES_HOST):"
ask POSTGRES_PORT "Port shown there (usually 5432, becomes POSTGRES_PORT):"
ask POSTGRES_USER "Username shown there (becomes POSTGRES_USER):"
ask_secret POSTGRES_PASSWORD "Password shown there (becomes POSTGRES_PASSWORD):"
note "Kept in memory for the rest of this run only — not written to disk."

# ── Stage 2: Web service ───────────────────────────────────────────────────
stage "Render: create the free web service"
say "This builds docker/odoo-render.Dockerfile from the repo on every push"
say "to main/19.0."
open_url "https://dashboard.render.com/new/web"
step "Connect the GitHub repo (grant Render access if this is the first"
step "service from this repo)."
step "Branch: main/19.0 — must already exist (see prerequisite above)."
step "Runtime: Docker. Dockerfile Path: docker/odoo-render.Dockerfile."
step "Root Directory: leave blank (repo root)."
step "Instance Type: Free."
step "Auto-Deploy: On Commit (this is what makes a release-PR merge deploy"
step "without any manual dashboard step)."
say "Render auto-detects the container port from the Dockerfile's"
say "EXPOSE 8069 — no PORT variable to set."
note "Don't click 'Create Web Service' yet if the next stage's env vars form"
note "is on the same page — fill those in first, then create."
pause "Press Enter once the web service form is filled in (don't submit yet)"

# ── Stage 3: Environment variables ─────────────────────────────────────────
stage "Render: set the web service's environment variables"
say "Odoo's entrypoint (docker/odoo-render-entrypoint.sh) requires the five"
say "starred below to boot — it validates each and refuses to start if one"
say "is missing or malformed. POSTGRES_PORT is optional (defaults to 5432)."
step "In the web service's Environment tab, add each variable below."
ODOO_ADMIN_PASSWORD=$(openssl rand -base64 24 2>/dev/null | tr -d '/+=\n' | cut -c1-32 || true)
if [[ -n "$ODOO_ADMIN_PASSWORD" ]]; then
  note "Generated a random Odoo master password (shown once, save it now):"
  printf '  %s%s%s\n' "$BOLD" "$ODOO_ADMIN_PASSWORD" "$RESET"
else
  ask_secret ODOO_ADMIN_PASSWORD "openssl unavailable — paste an admin master password:"
fi
step "* ODOO_ADMIN_PASSWORD = the value above (this is the master/admin_passwd,"
step "  not a login password — needed for db management operations)."
step "* ODOO_DB = $ODOO_DB"
step "* POSTGRES_HOST = $POSTGRES_HOST"
step "  POSTGRES_PORT = $POSTGRES_PORT (optional — omit to default to 5432)"
step "* POSTGRES_USER = $POSTGRES_USER"
step "* POSTGRES_PASSWORD = (the database password from Stage 1)"
step "Save changes, then click 'Create Web Service' (or 'Save, rebuild, and"
step "deploy' if the service already exists)."
SKIPPED+=("store ODOO_ADMIN_PASSWORD somewhere durable (e.g. a password manager) — it is not saved anywhere by this script")
pause "Press Enter once the web service is created and deploying"

# ── Stage 4: First deploy ──────────────────────────────────────────────────
stage "Verify the first deploy is live"
say "The first boot runs the self-healing init (crm_methodology --with-demo)"
say "before Odoo starts serving, so it's slower than later boots."
step "Watch the deploy log until it prints the server listening on 8069."
ask RENDER_URL "Paste the service's onrender.com URL shown in the dashboard:"
open_url "$RENDER_URL"
confirm "Does the Odoo login/CRM page load at that URL?" \
  && note "Demo instance is live." \
  || SKIPPED+=("first deploy did not come up cleanly at $RENDER_URL — check the deploy logs")

# ── Stage 5: Verify release-PR auto-deploy ─────────────────────────────────
stage "Verify a release PR triggers redeploy with no dashboard step"
say "This is the actual acceptance bar for the CD pipeline: merging"
say "dev/19.0 into main/19.0 must redeploy on its own."
step "Open a PR from dev/19.0 into main/19.0, wait for lint to pass, and merge it"
step "(or merge a trivial no-op change if there's nothing pending)."
open_url "https://dashboard.render.com/"
confirm "After the merge, did Render start a new deploy automatically" \
  && note "Auto-deploy on push to main/19.0 confirmed working." \
  || SKIPPED+=("auto-deploy on main/19.0 push did not fire — check the web service's GitHub connection and Auto-Deploy setting")

finish
