#!/usr/bin/env pwsh
<#
    A wizard walks a human through a manual procedure, step by step.
    Generated by the /wizard skill; PowerShell port of render-demo-setup.sh
    for use in a PowerShell terminal (the bash version needs Git Bash/WSL).

    Everything above the "STAGES" marker is the wizard library: do not
    hand-edit it. Author the per-step stages below the marker.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# This wizard never persists to .env or GitHub secrets (see banner text), so
# unlike the bash template this port has no write_env/set_secret equivalents.
# ──────────────────────────────────────────────────────────────────────────

$script:TotalStages = 0
$script:StageIndex = 0
$script:Skipped = [System.Collections.Generic.List[string]]::new()

function Clear-WizardScreen {
    try { Clear-Host } catch {}
}

# Show-Banner "Title": the opening frame, what this wizard does.
function Show-Banner {
    param([string]$Title)
    Clear-WizardScreen
    Write-Host ""
    Write-Host "  $Title" -ForegroundColor Cyan
    Write-Host "  $($script:TotalStages) stages" -ForegroundColor DarkGray
    Write-Host ""
    Write-Host "  You drive the browser; this wizard tells you exactly what to do and" -ForegroundColor DarkGray
    Write-Host "  captures the values you copy back. Stop any time with Ctrl-C and" -ForegroundColor DarkGray
    Write-Host "  re-run later." -ForegroundColor DarkGray
    Wait-ForEnter "Ready to start?"
}

# Start-Stage "Name": clears the screen, announces a stage, shows progress.
function Start-Stage {
    param([string]$Name)
    Clear-WizardScreen
    $script:StageIndex++
    Write-Host ""
    Write-Host "  > Stage $($script:StageIndex)/$($script:TotalStages) - $Name" -ForegroundColor Cyan
}

function Write-Say  { param([string]$Text) Write-Host "  $Text" }
function Write-Step {
    param([string]$Text)
    Write-Host -NoNewline "  "
    Write-Host -NoNewline "*" -ForegroundColor Cyan
    Write-Host " $Text"
}
function Write-Note { param([string]$Text) Write-Host "  $Text" -ForegroundColor DarkGray }
function Write-Warn { param([string]$Text) Write-Host "  ! $Text" -ForegroundColor Yellow }

# Open-WizardUrl URL: opens it in the human's default browser.
function Open-WizardUrl {
    param([string]$Url)
    Write-Host "  -> opening $Url" -ForegroundColor Green
    try {
        Start-Process $Url | Out-Null
    } catch {
        Write-Warn "couldn't open a browser; visit it manually: $Url"
    }
}

# Wait-ForEnter "msg": waits for the human to confirm they've done the manual part.
function Wait-ForEnter {
    param([string]$Message = "Press Enter to continue")
    Write-Host -NoNewline "  $Message " -ForegroundColor DarkGray
    [void](Read-Host)
}

# Confirm-Action "question": y/N gate; returns $true on yes.
function Confirm-Action {
    param([string]$Question)
    $reply = Read-Host "  ? $Question [y/N]"
    return $reply -match '^[Yy]'
}

# Read-Ask "Prompt": reads a visible value and returns it.
function Read-Ask {
    param([string]$Prompt)
    return Read-Host "  $Prompt"
}

# Read-AskSecret "Prompt": reads a hidden value and returns it as plain text
# (kept in memory only for this run — never written to disk).
function Read-AskSecret {
    param([string]$Prompt)
    $secure = Read-Host "  $Prompt" -AsSecureString
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        return [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    } finally {
        [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }
}

# New-RandomPassword: a random alphanumeric password, no external tool needed.
function New-RandomPassword {
    param([int]$Length = 32)
    $bytes = [byte[]]::new(32)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $encoded = [Convert]::ToBase64String($bytes) -replace '[/+=]', ''
    if ($encoded.Length -ge $Length) { return $encoded.Substring(0, $Length) }
    return $encoded
}

# Show-Finish: closing summary of anything left to do by hand.
function Show-Finish {
    Clear-WizardScreen
    Write-Host ""
    Write-Host "  Setup complete" -ForegroundColor Green
    if ($script:Skipped.Count -gt 0) {
        Write-Host ""
        Write-Warn "still to do by hand:"
        foreach ($item in $script:Skipped) { Write-Note "  - $item" }
    }
    Write-Host ""
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: mirrors scripts/render-demo-setup.sh. Keep the two in sync.
# ──────────────────────────────────────────────────────────────────────────

$script:TotalStages = 5

Show-Banner "Render demo instance setup (ADR 0006)"

Write-Say "This wizard provisions the client-demo instance on Render's free tier:"
Write-Say "a free Postgres database + a free web service built from"
Write-Say "docker/odoo-render.Dockerfile, wired to auto-deploy on push to"
Write-Say "main/19.0. Nothing here is written to .env or GitHub secrets - every"
Write-Say "value goes straight into Render's own dashboard, since that's the only"
Write-Say "place production config for this instance lives."
Write-Note "Prerequisite: the main/19.0 branch must already exist in GitHub and be"
Write-Note "protected (reviewed PR + passing CI required, no direct pushes). This"
Write-Note "is a one-time repo-admin step done via 'gh api .../branches/main%2F19.0/protection'"
Write-Note "(see docs/agents/sdlc.md) - it doesn't need production credentials, so"
Write-Note "it isn't a stage in this wizard. Verify it before continuing:"
Write-Note "  gh api repos/<owner>/<repo>/branches/main%2F19.0/protection"

# ── Stage 1: Postgres database ─────────────────────────────────────────────
Start-Stage "Render: create the free Postgres database"
Write-Say "Render's free Postgres expires 30 days after creation (14-day grace"
Write-Say "period) - see ADR 0006 for why the entrypoint self-heals around this"
Write-Say "instead of relying on a Pre-Deploy Command."
Open-WizardUrl "https://dashboard.render.com/new/database"
Write-Step "Name it (e.g. agentic-erp-demo-db), keep the default Postgres version."
Write-Step "Set Instance Type to Free."
Write-Step "Click 'Create Database' and wait for status to become 'Available'."
Write-Step "On the database's page, open the 'Connect' tab and switch to"
Write-Step "'Internal Database URL' (same-region traffic, no bandwidth cost)."
$OdooDb = Read-Ask "Database name shown there (this becomes ODOO_DB):"
$PostgresHost = Read-Ask "Hostname shown there (Internal, becomes POSTGRES_HOST):"
$PostgresPort = Read-Ask "Port shown there (usually 5432, becomes POSTGRES_PORT):"
$PostgresUser = Read-Ask "Username shown there (becomes POSTGRES_USER):"
$PostgresPassword = Read-AskSecret "Password shown there (becomes POSTGRES_PASSWORD):"
Write-Note "Kept in memory for the rest of this run only - not written to disk."

# ── Stage 2: Web service ───────────────────────────────────────────────────
Start-Stage "Render: create the free web service"
Write-Say "This builds docker/odoo-render.Dockerfile from the repo on every push"
Write-Say "to main/19.0."
Open-WizardUrl "https://dashboard.render.com/new/web"
Write-Step "Connect the GitHub repo (grant Render access if this is the first"
Write-Step "service from this repo)."
Write-Step "Branch: main/19.0 - must already exist (see prerequisite above)."
Write-Step "Runtime: Docker. Dockerfile Path: docker/odoo-render.Dockerfile."
Write-Step "Root Directory: leave blank (repo root)."
Write-Step "Instance Type: Free."
Write-Step "Auto-Deploy: On Commit (this is what makes a release-PR merge deploy"
Write-Step "without any manual dashboard step)."
Write-Say "Render auto-detects the container port from the Dockerfile's"
Write-Say "EXPOSE 8069 - no PORT variable to set."
Write-Note "Don't click 'Create Web Service' yet if the next stage's env vars form"
Write-Note "is on the same page - fill those in first, then create."

# ── Stage 3: Environment variables ─────────────────────────────────────────
Start-Stage "Render: set the web service's environment variables"
Write-Say "Odoo's entrypoint (docker/odoo-render-entrypoint.sh) requires the five"
Write-Say "starred below to boot - it validates each and refuses to start if one"
Write-Say "is missing or malformed. POSTGRES_PORT is optional (defaults to 5432)."
Write-Step "In the web service's Environment tab, add each variable below."
$OdooAdminPassword = New-RandomPassword
Write-Note "Generated a random Odoo master password (shown once, save it now):"
Write-Host "  $OdooAdminPassword" -ForegroundColor White
Write-Step "* ODOO_ADMIN_PASSWORD = the value above (this is the master/admin_passwd,"
Write-Step "  not a login password - needed for db management operations)."
Write-Step "* ODOO_DB = $OdooDb"
Write-Step "* POSTGRES_HOST = $PostgresHost"
Write-Step "  POSTGRES_PORT = $PostgresPort (optional - omit to default to 5432)"
Write-Step "* POSTGRES_USER = $PostgresUser"
Write-Step "* POSTGRES_PASSWORD = (the database password from Stage 1)"
Write-Step "Save changes, then click 'Create Web Service' (or 'Save, rebuild, and"
Write-Step "deploy' if the service already exists)."
$script:Skipped.Add("store ODOO_ADMIN_PASSWORD somewhere durable (e.g. a password manager) - it is not saved anywhere by this script")

# ── Stage 4: First deploy ──────────────────────────────────────────────────
Start-Stage "Verify the first deploy is live"
Write-Say "The first boot runs the self-healing init (crm_methodology --with-demo)"
Write-Say "before Odoo starts serving, so it's slower than later boots."
Write-Step "Watch the deploy log until it prints the server listening on 8069."
$RenderUrl = Read-Ask "Paste the service's onrender.com URL shown in the dashboard:"
Open-WizardUrl $RenderUrl
if (Confirm-Action "Does the Odoo login/CRM page load at that URL?") {
    Write-Note "Demo instance is live."
} else {
    $script:Skipped.Add("first deploy did not come up cleanly at $RenderUrl - check the deploy logs")
}

# ── Stage 5: Verify release-PR auto-deploy ─────────────────────────────────
Start-Stage "Verify a release PR triggers redeploy with no dashboard step"
Write-Say "This is the actual acceptance bar for the CD pipeline: merging"
Write-Say "dev/19.0 into main/19.0 must redeploy on its own."
Write-Step "Open a PR from dev/19.0 into main/19.0 and get it reviewed/merged"
Write-Step "(or merge a trivial no-op change if there's nothing pending)."
Open-WizardUrl "https://dashboard.render.com/"
if (Confirm-Action "After the merge, did Render start a new deploy automatically") {
    Write-Note "Auto-deploy on push to main/19.0 confirmed working."
} else {
    $script:Skipped.Add("auto-deploy on main/19.0 push did not fire - check the web service's GitHub connection and Auto-Deploy setting")
}

Show-Finish
